version: '3'
services:
  tensorflowjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: tfjs-node:cpu
    env_file:
      - .env
    volumes:
      - "${root}:/root"
      - "${project}:/root/project"
    command: /bin/bash